# Generated by Django 2.0.2 on 2018-02-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('num_cpus', models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4'), ('8', '8'), ('16', '16')], default='2', max_length=8)),
                ('memory', models.CharField(choices=[('128', '128'), ('256', '256'), ('512', '512'), ('1024', '1024'), ('2048', '2048'), ('4096', '4096'), ('8192', '8192'), ('16384', '16384')], default='1024', max_length=8)),
                ('network', models.CharField(max_length=128)),
                ('config', models.TextField()),
            ],
        ),
    ]
