# Generated by Django 2.0.2 on 2018-02-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='status',
            field=models.CharField(default='unknown', editable=False, max_length=32),
        ),
    ]
