# Generated by Django 2.0.2 on 2018-02-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0002_virtualmachine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='log',
            field=models.TextField(default='EOF', editable=False),
        ),
    ]
