# Generated by Django 2.0.2 on 2018-02-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0003_virtualmachine_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='disk',
            field=models.PositiveIntegerField(default='40'),
        ),
    ]
