# Generated by Django 2.0.2 on 2018-02-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0004_virtualmachine_disk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='config',
            field=models.TextField(default='\n#!/bin/bash\nuname -a\necho "Starting to configure ..."\n\n# ======= Input your configuration process =======\n\nexit 0\n'),
        ),
    ]
