# Generated by Django 2.0.2 on 2018-02-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0006_auto_20180209_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='config',
            field=models.TextField(default='#!/bin/bash\necho "Virtual Machine provision is done: `date`"\nuname -a\necho "Starting to configure ..."\n\n# ======= Input your configuration process =======\n\nexit 0\n'),
        ),
    ]
