# Generated by Django 2.0.2 on 2018-02-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0010_auto_20180216_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
