# Generated by Django 2.0.2 on 2018-02-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0011_auto_20180216_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='sign',
            field=models.CharField(default='0', editable=False, max_length=128),
        ),
    ]
