# Generated by Django 2.0.2 on 2018-02-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0012_virtualmachine_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualmachine',
            old_name='sign',
            new_name='cursign',
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='finsign',
            field=models.CharField(default='0', editable=False, max_length=128),
        ),
    ]
